# make use of vm's
sudo: 'required'

dist: trusty

language: java

#sources:
  #- google-chrome

packages:
  - realpath 
  - python 
  - python-pip
  - docker-ce

jdk:
  - oraclejdk8
  
# have the docker service set up (we'll
# update it later)
services:
  - 'docker'

# prepare the machine before any code
# installation scripts
before_install:
#  - './.travis/main.sh'
  
script:
#  - './gradlew export'
#  - './.travis/build-docker.sh'
