package pnnl.goss.gridappsd.dto;

import java.io.Serializable;

public class SimulationConfig  implements Serializable {
	
	//eg, forward backward sweeper
	public static String power_flow_solver_method;
	//how long the simulation should last (in seconds), default 1 day 
	public static long duration = 86400;
	//simulation id (auto-generated by process manager)
	public static String simulation_id;
	//??
	public static String simulator;
	//time that you want the simulation to start, expected format yyyy-MM-dd HH:mm:ss 
	public static String start_time;

	
	//TODO change this to more detailed object about output??? maybe not needed
//	public static String[] output_object_mrid;
	//Default output, json message per timestep
	
	//getting rid of this for now, only 1 simulation at once
//	public static String[] simulator_name;

//	@Override
//	public String toString() {
//		return "ClassPojo [power_flow_solver_method = "
//				+ power_flow_solver_method + ", duration = " + duration
//				+ ", simulation_name = " + simulation_name + ", simulator = "
//				+ simulator + ", start_time = " + start_time
//				+ ", output_object_mrid = " + output_object_mrid
//				+ ", simulator_name = " + simulator_name + "]";
//	}
}